workflows:
  android-workflow:
    name: BoxMonitor Android Build
    max_build_duration: 60
    environment:
      android_signing:
        - keystore_reference
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build APK debug
        script: |
          cd $CM_BUILD_DIR
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
